version: '3.8'

services:
  transcribe-locally:
    image: mossly/transcribe-locally:v1.2.3
    container_name: transcribe-locally
    ports:
      - "27027:27027"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transcription.rule=PathPrefix(`/`)"
      - "traefik.http.services.transcription.loadbalancer.server.port=27027"